#pragma linkage (main,optlink)

INT main(VOID);

#define MSGBOXID     	1001

#define ID_WINDOW    	99

#define M_GAME		300
#define M_NEWEASY       310
#define M_NEWMEDI       311
#define M_NEWHARD       312

#define M_NEWGAME       301
#define M_EXIT          302
#define M_TIMER         330

#define M_HELP          303
#define M_ABOUT         320

#define BM_WIDTH     	256 // sorry :(
#define BM_HEIGHT    	256

#define BM_0	     	100
#define BM_1	     	101
#define BM_2	     	102
#define BM_3	     	103
#define BM_4	     	104
#define BM_5	     	105
#define BM_6	     	106
#define BM_7	     	107
#define BM_8	     	108
#define BM_9	     	109
#define BM_BOMB    	110
#define BM_CHECK    	111
#define BM_ILL		112
#define BM_FAIL		113
#define BM_ASK1         119
#define BM_ASK2         120

/* window controls (UNUSED)*/

#define BM_FACED	114
#define BM_FACE1	115
#define BM_FACE2	116
#define BM_FACE3	117
#define BM_FACE4	118

#define BM_EMPTY        121

/* border :-[   ] */

#define BM_B1		122
#define BM_B2		123
#define BM_B3		124
#define BM_B4		125
#define BM_B5		126
#define BM_B6		127
#define BM_B7		128
#define BM_B8		129

#define BM_LAST		129
